### ISSUE TITLE
[Tracking issue] Improve documentation

### ISSUE THREAD

**Issue by nickschot** [postlight/lux#698]
As docs are currently still lacking in some area's it seems like a good idea to get a list of missing docs together in this issue.

Please put anything you miss in a comment and they will be added to the list. When something is implemented or in a PR the issue will be updated with a reference to the PR.

**Documentation improvements**
- [ ] Guide
  - [ ] Configuration
    - [ ] Database
    - [ ] Environments
    - [ ] CORS
  - [ ] CLI
    - [ ] Generators
  - [ ] Router
    - [ ] Options (i.e. "only")
    - [ ] Defining custom actions
  - [ ] Database
    - [ ] Migrations
    - [ ] Seeds
  - [ ] Deployment
    - [ ] Serving the API for production
  - [ ] Debugger (see #685)
- [ ] API Reference (TBA)
