### ISSUE TITLE
[Tracking issue] Improving build performance & experience

### ISSUE THREAD

**Issue by nickschot** [postlight/lux#701]
*   **Platform**:
*   **Database**:
*   **Lux Version**:
*   **Node Version**:

Build performance can still be improved a lot. Especially rebuilds take too much time right now. The main tasks which consume time are the bundling (rollup) and the forking/reloading of the process.

- [ ] Enable incremental rebuilds for Rollup ( see #700 )
- [ ] Improve performance of loading new bundle
- [ ] Prevent duplicate processes (cancel build on new change?)

**Comment by nickschot** [comment]
We are losing a lot of time because the worker.once('exit') is never called in time (so we always get the 5 second timeout).

**Comment by nickschot** [comment]
For the last 2 points we still need some reliable reproduction. I encountered it often but have not yet been able to reliably reproduce. Likely timing/lock issue in the watcher.
